apiVersion: v1
kind: Service
metadata:
  name: encryption-sidecar
  namespace: etcd-poc
  labels:
    app: etcd-client
spec:
  type: ClusterIP
  selector:
    app: etcd-client
  ports:
    - name: http
      port: 5000
      targetPort: 5000
