repeats: 5

tests:
  - test_id: T01
    overlay: e0-plaintext
    workload: w1_put_only.yaml
    payload: payload_s.yaml
    concurrency: c1.yaml

  - test_id: T02
    overlay: e0-plaintext
    workload: w3_read_mostly.yaml
    payload: payload_m.yaml
    concurrency: c2.yaml

  - test_id: T03
    overlay: e0-plaintext
    workload: w4_balanced.yaml
    payload: payload_l.yaml
    concurrency: c3.yaml

  - test_id: T04
    overlay: e1-native-etcd-encryption
    workload: w1_put_only.yaml
    payload: payload_s.yaml
    concurrency: c1.yaml

  - test_id: T05
    overlay: e1-native-etcd-encryption
    workload: w3_read_mostly.yaml
    payload: payload_m.yaml
    concurrency: c2.yaml

  - test_id: T06
    overlay: e1-native-etcd-encryption
    workload: w4_balanced.yaml
    payload: payload_l.yaml
    concurrency: c3.yaml

  - test_id: T07
    overlay: e2-side
