apiVersion: apps/v1
kind: Deployment
metadata:
  name: bench-client
  namespace: etcd-bench
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bench-client
  template:
    metadata:
      labels:
        app: bench-client
    spec:
      containers:
        - name: bench-client
          image: killoscully/etcd-bench-client:latest
          imagePullPolicy: Always
          env:
            - name: ETCD_ENDPOINT
              value: http://etcd:2379
          command: ["sh", "-lc", "sleep infinity"]
          volumeMounts:
            - name: bench-configs
              mountPath: /bench/configs
              readOnly: true
      volumes:
        - name: bench-configs
          configMap:
            name: bench-configs
